### ISSUE TITLE
how to build/run locally?

### ISSUE THREAD

**Issue by bradparks** [HubertK05/banban#4]
What's the basic instructions to build and run this?

I'm a newb here for sure, but tried

```
$ npm install
$ cargo run
```

and it opens up a blank window... Thanks!

**Comment by HubertK05** [comment]
This is a Tauri app, and to run it locally you need to run `npm run tauri dev`. This command sets up both frontend and Rust, and `cargo run` only builds and runs the backend, which results in no content displayed to the user. Hope this helps!

**Comment by bradparks** [comment]
nice! thanks - tried and $$$$ !
